<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ===== Lithium Batteries =====
            [
                'name' => 'Westwood 51.2V 100Ah Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Westwood',
                'price' => 198000,
                'unit' => '5kWh',
                'warranty' => null,
                'specs' => ['Voltage: 51.2V', 'Capacity: 100Ah', 'Energy: 5kWh'],
            ],
            [
                'name' => 'Pylontech Fidus Plus 16kWh',
                'category' => 'Lithium Batteries',
                'brand' => 'Pylontech',
                'price' => 705000,
                'unit' => '16kWh',
                'warranty' => null,
                'specs' => ['Capacity: 16kWh'],
            ],
            [
                'name' => 'Pylontech Fidus Powerwall 5kWh',
                'category' => 'Lithium Batteries',
                'brand' => 'Pylontech',
                'price' => 265000,
                'unit' => '5kWh',
                'warranty' => null,
                'specs' => ['Capacity: 5kWh'],
            ],
            [
                'name' => 'Dyness Powerbrick SC 16kWh',
                'category' => 'Lithium Batteries',
                'brand' => 'Dyness',
                'price' => 675000,
                'unit' => '16kWh',
                'warranty' => null,
                'specs' => ['Capacity: 16kWh'],
            ],
            [
                'name' => 'Dyness DL5.0C 5kWh',
                'category' => 'Lithium Batteries',
                'brand' => 'Dyness',
                'price' => 250000,
                'unit' => '5kWh',
                'warranty' => null,
                'specs' => ['Capacity: 5kWh'],
            ],
            [
                'name' => 'Goodwe 5kWh 100Ah Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Goodwe',
                'price' => 270000,
                'unit' => '5kWh',
                'warranty' => '10 Years',
                'specs' => ['Capacity: 5kWh', 'Current: 100Ah'],
            ],
            [
                'name' => 'Goodwe 14.3kWh 280Ah Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Goodwe',
                'price' => 720000,
                'unit' => '14.3kWh',
                'warranty' => '10 Years',
                'specs' => ['Capacity: 14.3kWh', 'Current: 280Ah'],
            ],
            [
                'name' => 'Goodwe 50kWh HV Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Goodwe',
                'price' => 2800000,
                'unit' => '50kWh',
                'warranty' => '7 Years',
                'specs' => ['Capacity: 50kWh', 'Type: HV'],
            ],
            [
                'name' => 'Soluna 2.56kWh Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Soluna',
                'price' => 150000,
                'unit' => '2.56kWh',
                'warranty' => '5 Years',
                'specs' => ['Capacity: 2.56kWh'],
            ],
            [
                'name' => 'Soluna 5kWh IP20 Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Soluna',
                'price' => 245000,
                'unit' => '5kWh',
                'warranty' => '7 Years',
                'specs' => ['Capacity: 5kWh', 'Protection: IP20'],
            ],
            [
                'name' => 'Soluna 10kWh IP65 Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Soluna',
                'price' => 600000,
                'unit' => '10kWh',
                'warranty' => '10 Years',
                'specs' => ['Capacity: 10kWh', 'Protection: IP65'],
            ],
            [
                'name' => 'Soluna 16kWh IP65 Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Soluna',
                'price' => 730000,
                'unit' => '16kWh',
                'warranty' => '10 Years',
                'specs' => ['Capacity: 16kWh', 'Protection: IP65'],
            ],
            [
                'name' => 'Soluna 32kWh IP65 Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Soluna',
                'price' => 1450000,
                'unit' => '32kWh',
                'warranty' => '10 Years',
                'specs' => ['Capacity: 32kWh', 'Protection: IP65'],
            ],
            [
                'name' => 'DJDC 5kW Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'DJDC',
                'price' => 245000,
                'unit' => '5kWh',
                'warranty' => null,
                'specs' => ['Capacity: 5kWh'],
            ],
            [
                'name' => 'DJDC 10kW Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'DJDC',
                'price' => 480000,
                'unit' => '10kWh',
                'warranty' => null,
                'specs' => ['Capacity: 10kWh'],
            ],
            [
                'name' => 'DJDC 16kW Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'DJDC',
                'price' => 650000,
                'unit' => '16kWh',
                'warranty' => null,
                'specs' => ['Capacity: 16kWh'],
            ],
            [
                'name' => 'Knox Powerwall 6.0 Lithium Battery',
                'category' => 'Lithium Batteries',
                'brand' => 'Knox',
                'price' => 232000,
                'unit' => '6kWh',
                'warranty' => null,
                'specs' => ['Capacity: 6kWh'],
            ],

            // ===== On-Grid Inverters =====
            [
                'name' => 'Goodwe GW10kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 170000,
                'unit' => '10kW',
                'warranty' => '10 Years',
                'specs' => ['Power: 10kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW15kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 220000,
                'unit' => '15kW',
                'warranty' => '10 Years',
                'specs' => ['Power: 15kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW20kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 280000,
                'unit' => '20kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 20kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW25kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 325000,
                'unit' => '25kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 25kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW50kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 475000,
                'unit' => '50kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 50kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW125kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 995000,
                'unit' => '125kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 125kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Goodwe GW150kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Goodwe',
                'price' => 1240000,
                'unit' => '150kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 150kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 10kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 175000,
                'unit' => '10kW',
                'warranty' => null,
                'specs' => ['Power: 10kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 12kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 198000,
                'unit' => '12kW',
                'warranty' => null,
                'specs' => ['Power: 12kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 15kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 218000,
                'unit' => '15kW',
                'warranty' => null,
                'specs' => ['Power: 15kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 20kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 275000,
                'unit' => '20kW',
                'warranty' => null,
                'specs' => ['Power: 20kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 25kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 305000,
                'unit' => '25kW',
                'warranty' => null,
                'specs' => ['Power: 25kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 30kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 348000,
                'unit' => '30kW',
                'warranty' => null,
                'specs' => ['Power: 30kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 40kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 460000,
                'unit' => '40kW',
                'warranty' => null,
                'specs' => ['Power: 40kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 60kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 580000,
                'unit' => '60kW',
                'warranty' => null,
                'specs' => ['Power: 60kW', 'Type: On-Grid'],
            ],
            [
                'name' => 'Sineng 125kW On-Grid Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Sineng',
                'price' => 895000,
                'unit' => '125kW',
                'warranty' => null,
                'specs' => ['Power: 125kW', 'Type: On-Grid'],
            ],

            // ===== Hybrid Inverters (Goodwe) =====
            [
                'name' => 'Goodwe 6kW 1-Ph Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 225000,
                'unit' => '6kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 6kW', 'Phase: Single Phase', 'Type: Hybrid'],
            ],
            [
                'name' => 'Goodwe 8kW 1-Ph Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 340000,
                'unit' => '8kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 8kW', 'Phase: Single Phase', 'Type: Hybrid'],
            ],
            [
                'name' => 'Goodwe 10kW 1-Ph Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 410000,
                'unit' => '10kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 10kW', 'Phase: Single Phase', 'Type: Hybrid'],
            ],
            [
                'name' => 'Goodwe 12kW 1-Ph Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 440000,
                'unit' => '12kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 12kW', 'Phase: Single Phase', 'Type: Hybrid'],
            ],
            [
                'name' => 'Goodwe 12kW 3-Ph Hybrid Inverter LV',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 515000,
                'unit' => '12kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 12kW', 'Phase: Three Phase', 'Type: Hybrid LV'],
            ],
            [
                'name' => 'Goodwe 15kW 3-Ph Hybrid Inverter LV',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 620000,
                'unit' => '15kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 15kW', 'Phase: Three Phase', 'Type: Hybrid LV'],
            ],
            [
                'name' => 'Goodwe 20kW 3-Ph Hybrid Inverter LV',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 820000,
                'unit' => '20kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 20kW', 'Phase: Three Phase', 'Type: Hybrid LV'],
            ],
            [
                'name' => 'Goodwe 50kW 3-Ph Hybrid Inverter HV',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 1450000,
                'unit' => '50kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 50kW', 'Phase: Three Phase', 'Type: Hybrid HV'],
            ],
            [
                'name' => 'Goodwe 100kW 3-Ph Hybrid Inverter HV',
                'category' => 'Hybrid Inverters',
                'brand' => 'Goodwe',
                'price' => 2200000,
                'unit' => '100kW',
                'warranty' => '5 Years',
                'specs' => ['Power: 100kW', 'Phase: Three Phase', 'Type: Hybrid HV'],
            ],

            // ===== Hybrid Inverters (GoodWe Three Phase) =====
            [
                'name' => 'GoodWe 12kW Hybrid Three Phase Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'GoodWe',
                'price' => 525000,
                'unit' => '12kW',
                'warranty' => null,
                'specs' => ['Power: 12kW', 'Phase: Three Phase', 'Type: Hybrid'],
            ],
            [
                'name' => 'GoodWe 15kW Hybrid Three Phase Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'GoodWe',
                'price' => 625000,
                'unit' => '15kW',
                'warranty' => null,
                'specs' => ['Power: 15kW', 'Phase: Three Phase', 'Type: Hybrid'],
            ],

            // ===== Hybrid Inverters (Anicsun IP66) =====
            [
                'name' => 'Anicsun 6kW IP66 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 190000,
                'unit' => '6kW',
                'warranty' => null,
                'specs' => ['Power: 6kW', 'Protection: IP66', 'Model: PV9000'],
            ],
            [
                'name' => 'Anicsun 8kW IP66 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 285000,
                'unit' => '8kW',
                'warranty' => null,
                'specs' => ['Power: 8kW', 'Protection: IP66', 'Model: PV12000'],
            ],

            // ===== Hybrid Inverters (Anicsun IP21) =====
            [
                'name' => 'Anicsun 4kW EX4 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 95000,
                'unit' => '4kW',
                'warranty' => null,
                'specs' => ['Power: 4kW', 'Model: EX4', 'PV5000'],
            ],
            [
                'name' => 'Anicsun 4kW VX4+ Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 105000,
                'unit' => '4kW',
                'warranty' => null,
                'specs' => ['Power: 4kW', 'Model: VX4+', 'PV5600'],
            ],
            [
                'name' => 'Anicsun 6kW EX6 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 115000,
                'unit' => '6kW',
                'warranty' => null,
                'specs' => ['Power: 6kW', 'Model: EX6', 'PV6500'],
            ],
            [
                'name' => 'Anicsun 6.2kW IX Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 135000,
                'unit' => '6.2kW',
                'warranty' => null,
                'specs' => ['Power: 6.2kW', 'Model: IX', 'PV8000'],
            ],
            [
                'name' => 'Anicsun 6.2kW Dual Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 145000,
                'unit' => '6.2kW',
                'warranty' => null,
                'specs' => ['Power: 6.2kW', 'Model: Dual', 'PV8000'],
            ],
            [
                'name' => 'Anicsun 8kW UX8 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Anicsun',
                'price' => 235000,
                'unit' => '8kW',
                'warranty' => null,
                'specs' => ['Power: 8kW', 'Model: UX8', 'PV10000'],
            ],

            // ===== Hybrid Inverters (DJDC) =====
            [
                'name' => 'DJDC 3.5kW PV5000 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 91500,
                'unit' => '3.5kW',
                'warranty' => null,
                'specs' => ['Power: 3.5kW', 'Model: PV5000'],
            ],
            [
                'name' => 'DJDC 5.5kW PV6000 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 103000,
                'unit' => '5.5kW',
                'warranty' => null,
                'specs' => ['Power: 5.5kW', 'Model: PV6000'],
            ],
            [
                'name' => 'DJDC 10.2kW PV12000 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 187000,
                'unit' => '10.2kW',
                'warranty' => null,
                'specs' => ['Power: 10.2kW', 'Model: PV12000'],
            ],
            [
                'name' => 'DJDC Max Pro 11kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 290000,
                'unit' => '11kW',
                'warranty' => null,
                'specs' => ['Power: 11kW', 'Series: Max Pro'],
            ],
            [
                'name' => 'DJDC Eco 6kW IP66 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 245000,
                'unit' => '6kW',
                'warranty' => null,
                'specs' => ['Power: 6kW', 'Protection: IP66', 'Series: Eco'],
            ],
            [
                'name' => 'DJDC Eco 10kW IP66 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 395000,
                'unit' => '10kW',
                'warranty' => null,
                'specs' => ['Power: 10kW', 'Protection: IP66', 'Series: Eco'],
            ],
            [
                'name' => 'DJDC Fini 5kW PV5500 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 120000,
                'unit' => '5kW',
                'warranty' => null,
                'specs' => ['Power: 5kW', 'Series: Fini', 'Model: PV5500'],
            ],
            [
                'name' => 'DJDC Fini PV7000 Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'DJDC',
                'price' => 145000,
                'unit' => null,
                'warranty' => null,
                'specs' => ['Series: Fini', 'Model: PV7000'],
            ],

            // ===== Hybrid Inverters (Sineng) =====
            [
                'name' => 'Sineng 10kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Sineng',
                'price' => 415000,
                'unit' => '10kW',
                'warranty' => null,
                'specs' => ['Power: 10kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Sineng 15kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Sineng',
                'price' => 515000,
                'unit' => '15kW',
                'warranty' => null,
                'specs' => ['Power: 15kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Sineng 25kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Sineng',
                'price' => 655000,
                'unit' => '25kW',
                'warranty' => null,
                'specs' => ['Power: 25kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Sineng 33kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Sineng',
                'price' => 745000,
                'unit' => '33kW',
                'warranty' => null,
                'specs' => ['Power: 33kW', 'Type: Hybrid'],
            ],

            // ===== Hybrid Inverters (Solis) =====
            [
                'name' => 'Solis 6kW Hybrid Plus Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 245000,
                'unit' => '6kW',
                'warranty' => null,
                'specs' => ['Power: 6kW', 'Type: Hybrid Plus'],
            ],
            [
                'name' => 'Solis 6kW Plus Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 240000,
                'unit' => '6kW',
                'warranty' => null,
                'specs' => ['Power: 6kW'],
            ],
            [
                'name' => 'Solis 8kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 345000,
                'unit' => '8kW',
                'warranty' => null,
                'specs' => ['Power: 8kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Solis 10kW Single Phase Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 410000,
                'unit' => '10kW',
                'warranty' => null,
                'specs' => ['Power: 10kW', 'Phase: Single Phase'],
            ],
            [
                'name' => 'Solis 15kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 645000,
                'unit' => '15kW',
                'warranty' => null,
                'specs' => ['Power: 15kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Solis 8kW Pro+ Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Solis',
                'price' => 350000,
                'unit' => '8kW',
                'warranty' => null,
                'specs' => ['Power: 8kW', 'Series: Pro+'],
            ],

            // ===== Hybrid Inverters (Nitrox) =====
            [
                'name' => 'Nitrox 3kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Nitrox',
                'price' => 190000,
                'unit' => '3kW',
                'warranty' => null,
                'specs' => ['Power: 3kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Nitrox 6.6kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Nitrox',
                'price' => 270000,
                'unit' => '6.6kW',
                'warranty' => null,
                'specs' => ['Power: 6.6kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Nitrox 10kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Nitrox',
                'price' => 535000,
                'unit' => '10kW',
                'warranty' => null,
                'specs' => ['Power: 10kW', 'Type: Hybrid'],
            ],
            [
                'name' => 'Nitrox 12kW Hybrid Inverter',
                'category' => 'Hybrid Inverters',
                'brand' => 'Nitrox',
                'price' => 750000,
                'unit' => '12kW',
                'warranty' => null,
                'specs' => ['Power: 12kW', 'Type: Hybrid'],
            ],

            // ===== Other Inverters =====
            [
                'name' => 'SunGrow 115kW Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'SunGrow',
                'price' => 1215000,
                'unit' => '115kW',
                'warranty' => null,
                'specs' => ['Power: 115kW'],
            ],
            [
                'name' => 'SunGrow 150kW Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'SunGrow',
                'price' => 1525000,
                'unit' => '150kW',
                'warranty' => null,
                'specs' => ['Power: 150kW'],
            ],
            [
                'name' => 'Huawei 115kW Inverter',
                'category' => 'On-Grid Inverters',
                'brand' => 'Huawei',
                'price' => 1270000,
                'unit' => '115kW',
                'warranty' => null,
                'specs' => ['Power: 115kW'],
            ],

            // ===== Solar Panels =====
            [
                'name' => 'Jinko 590W Solar Panel',
                'category' => 'Solar Panels',
                'brand' => 'Jinko',
                'price' => 46.85,
                'unit' => 'Per Watt',
                'warranty' => null,
                'specs' => ['Power: 590W', 'Price: 46.85/W'],
            ],
            [
                'name' => 'Jinko 655W Solar Panel',
                'category' => 'Solar Panels',
                'brand' => 'Jinko',
                'price' => 48.50,
                'unit' => 'Per Watt',
                'warranty' => null,
                'specs' => ['Power: 655W', 'Price: 48.5/W'],
            ],
            [
                'name' => 'American Solar 585W Solar Panel',
                'category' => 'Solar Panels',
                'brand' => 'American Solar',
                'price' => 43.75,
                'unit' => 'Per Watt',
                'warranty' => null,
                'specs' => ['Power: 585W', 'Price: 43.75/W'],
            ],
            [
                'name' => 'American Solar 590W Solar Panel',
                'category' => 'Solar Panels',
                'brand' => 'American Solar',
                'price' => 43.75,
                'unit' => 'Per Watt',
                'warranty' => null,
                'specs' => ['Power: 590W', 'Price: 43.75/W'],
            ],
            [
                'name' => 'JA 720W Solar Panel',
                'category' => 'Solar Panels',
                'brand' => 'JA Solar',
                'price' => 39.75,
                'unit' => 'Per Watt',
                'warranty' => null,
                'specs' => ['Power: 720W', 'Price: 39.75/W'],
            ],
        ];

        // Products that appeared in the WhatsApp channel after the initial catalog.
        $products = array_merge($products, [
            ['name' => 'Goodwe GW30kW On-Grid Inverter', 'category' => 'On-Grid Inverters', 'brand' => 'Goodwe', 'price' => 375000, 'unit' => '30kW', 'warranty' => '5 Years', 'specs' => ['Power: 30kW', 'Type: On-Grid']],
            ['name' => 'Goodwe 30kW 3-Ph Hybrid Inverter HV', 'category' => 'Hybrid Inverters', 'brand' => 'Goodwe', 'price' => 1050000, 'unit' => '30kW', 'warranty' => '5 Years', 'specs' => ['Power: 30kW', 'Phase: Three Phase', 'Type: Hybrid HV']],
            ['name' => 'Goodwe 16kWh IP65 Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Goodwe', 'price' => 750000, 'unit' => '16kWh', 'warranty' => '7 Years', 'specs' => ['Capacity: 16kWh', 'Protection: IP65']],
            ['name' => 'Soluna 5kWh IP65 Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Soluna', 'price' => 270000, 'unit' => '5kWh', 'warranty' => '7 Years', 'specs' => ['Capacity: 5kWh', 'Protection: IP65']],
            ['name' => 'HITHIUM 5.12kWh Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'HITHIUM', 'price' => 235000, 'unit' => '5.12kWh', 'warranty' => null, 'specs' => ['Capacity: 5.12kWh']],
            ['name' => 'Narada 48V 100Ah Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Narada', 'price' => 230000, 'unit' => '4.8kWh', 'warranty' => null, 'specs' => ['Voltage: 48V', 'Capacity: 100Ah']],
            ['name' => 'Narada 51.2V 100Ah Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Narada', 'price' => 240000, 'unit' => '5.12kWh', 'warranty' => null, 'specs' => ['Voltage: 51.2V', 'Capacity: 100Ah']],
            ['name' => 'Dyness Pro 5kW Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Dyness', 'price' => 265000, 'unit' => '5kWh', 'warranty' => null, 'specs' => ['Capacity: 5kWh', 'Series: Pro']],
            ['name' => 'Saj 50kW Hybrid Inverter HV', 'category' => 'Hybrid Inverters', 'brand' => 'Saj', 'price' => 1350000, 'unit' => '50kW', 'warranty' => null, 'specs' => ['Power: 50kW', 'Type: Hybrid HV']],
            ['name' => 'Saj 60kWh Lithium Battery', 'category' => 'Lithium Batteries', 'brand' => 'Saj', 'price' => 3330000, 'unit' => '60kWh', 'warranty' => null, 'specs' => ['Capacity: 60kWh']],
            ['name' => 'Itel 2.5kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Itel', 'price' => 130000, 'unit' => '2.5kW', 'warranty' => null, 'specs' => ['Power: 2.5kW', 'Type: Hybrid']],
            ['name' => 'Itel 5kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Itel', 'price' => 230000, 'unit' => '5kW', 'warranty' => null, 'specs' => ['Power: 5kW', 'Type: Hybrid']],
            ['name' => 'Itel 10kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Itel', 'price' => 450000, 'unit' => '10kW', 'warranty' => null, 'specs' => ['Power: 10kW', 'Type: Hybrid']],
            ['name' => 'Itel 16kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Itel', 'price' => 610000, 'unit' => '16kW', 'warranty' => null, 'specs' => ['Power: 16kW', 'Type: Hybrid']],
            ['name' => 'Solis 12kW SP Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 470000, 'unit' => '12kW', 'warranty' => null, 'specs' => ['Power: 12kW', 'Phase: Single Phase', 'Type: Hybrid LV']],
            ['name' => 'Solis 12kW 3P Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 535000, 'unit' => '12kW', 'warranty' => null, 'specs' => ['Power: 12kW', 'Phase: Three Phase', 'Type: Hybrid LV']],
            ['name' => 'Solis 18kW 3P Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 735000, 'unit' => '18kW', 'warranty' => null, 'specs' => ['Power: 18kW', 'Phase: Three Phase', 'Type: Hybrid LV']],
            ['name' => 'Solis 30kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 1130000, 'unit' => '30kW', 'warranty' => null, 'specs' => ['Power: 30kW', 'Type: Hybrid']],
            ['name' => 'Solis S6 6kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 229000, 'unit' => '6kW', 'warranty' => null, 'specs' => ['Power: 6kW', 'Phase: Single Phase', 'Protection: IP66', 'Series: S6']],
            ['name' => 'Solis S6 8kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 329000, 'unit' => '8kW', 'warranty' => null, 'specs' => ['Power: 8kW', 'Phase: Single Phase', 'Protection: IP66', 'Series: S6']],
            ['name' => 'Solis S6 10kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 390000, 'unit' => '10kW', 'warranty' => null, 'specs' => ['Power: 10kW', 'Phase: Single Phase', 'Protection: IP66', 'Series: S6']],
            ['name' => 'Solis S6 12kW Hybrid Inverter', 'category' => 'Hybrid Inverters', 'brand' => 'Solis', 'price' => 455000, 'unit' => '12kW', 'warranty' => null, 'specs' => ['Power: 12kW', 'Phase: Single Phase', 'Protection: IP66', 'Series: S6']],
            ['name' => 'Jinko 645W Solar Panel', 'category' => 'Solar Panels', 'brand' => 'Jinko', 'price' => 41.80, 'unit' => 'Per Watt', 'warranty' => null, 'specs' => ['Power: 645W', 'Series: Tiger 3.0', 'Grade: A']],
            ['name' => 'Jinko 725W Solar Panel', 'category' => 'Solar Panels', 'brand' => 'Jinko', 'price' => 41.25, 'unit' => 'Per Watt', 'warranty' => null, 'specs' => ['Power: 725W', 'Type: N-Type Bifacial']],
            ['name' => 'Trina 725W Solar Panel', 'category' => 'Solar Panels', 'brand' => 'Trina', 'price' => 39.25, 'unit' => 'Per Watt', 'warranty' => null, 'specs' => ['Power: 725W', 'Type: N-Type Bifacial']],
            ['name' => 'Longi X10 645W Solar Panel', 'category' => 'Solar Panels', 'brand' => 'Longi', 'price' => 43.75, 'unit' => 'Per Watt', 'warranty' => null, 'specs' => ['Power: 645W', 'Series: X10', 'Type: Bifacial', 'Grade: A']],
        ]);

        foreach ($products as $product) {
            $product += self::derivedFields($product);
            Product::updateOrCreate(
                ['slug' => Str::slug($product['name'])],
                $product,
            );
        }
    }

    /**
     * Derive phase and numeric capacity (kW for inverters, kWh for
     * batteries, panel watts / 1000) from the name and specs.
     */
    public static function derivedFields(array $product): array
    {
        $name = $product['name'];
        $haystack = $name.' '.implode(' ', $product['specs'] ?? []);

        $phase = null;
        if (preg_match('/1-?ph|single phase|\bSP\b/i', $haystack)) {
            $phase = 'Single Phase';
        } elseif (preg_match('/3-?ph|three phase|\b3P\b/i', $haystack)) {
            $phase = 'Three Phase';
        }

        $powerKw = null;
        if (preg_match('/(\d+(?:\.\d+)?)\s*kwh/i', $name, $m)) {
            $powerKw = (float) $m[1];
        } elseif (preg_match('/(\d+(?:\.\d+)?)\s*kw/i', $name, $m)) {
            $powerKw = (float) $m[1];
        } elseif (preg_match('/(\d{3,4})\s*w/i', $name, $m)) {
            $powerKw = (float) $m[1] / 1000;
        }

        return ['phase' => $phase, 'power_kw' => $powerKw];
    }
}
